### PR TITLE
Fix: URL Encode tool doesn't catch input error

### LINKED ISSUE #30: [Bug]: URL Encode tool doesn't catch input error
### Contact Details

_No response_

### What happened?

When typing some characters into the "Encoded" field such as `%`, a console error is thrown and the input does not add the character.

### What should have happened?

The input should have added the character, and a user friendly error message should have been displayed on the page, without throwing an error in the browser console.

### Notes

- A similar solution can be found in some of the other tools (e.g. JSON and HTML).
- A test case should be written for this situation to catch any future regressions.
- Optionally, it would be a good idea to write similar test cases for the other existing tools where appropriate.

### What browsers are you seeing the problem on?

Chrome

### Version

105.0.5195.134

### Relevant log output

```sh
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at onChange (url-encode-505d800127204f42.js:1:3489)
    at as (939-761c0c3295da9d71.js:1:19457)
    at G (939-761c0c3295da9d71.js:1:13804)
    at Object.aP (framework-9b5d6ec4444c80fa.js:11:16687)
    at aV (framework-9b5d6ec4444c80fa.js:11:16841)
    at framework-9b5d6ec4444c80fa.js:11:35726
    at dt (framework-9b5d6ec4444c80fa.js:11:35825)
    at du (framework-9b5d6ec4444c80fa.js:11:36239)
    at framework-9b5d6ec4444c80fa.js:11:41698
onChange @ url-encode-505d800127204f42.js:1
as @ 939-761c0c3295da9d71.js:1
G @ 939-761c0c3295da9d71.js:1
aP @ framework-9b5d6ec4444c80fa.js:11
aV @ framework-9b5d6ec4444c80fa.js:11
(anonymous) @ framework-9b5d6ec4444c80fa.js:11
dt @ framework-9b5d6ec4444c80fa.js:11
du @ framework-9b5d6ec4444c80fa.js:11
(anonymous) @ framework-9b5d6ec4444c80fa.js:11
h1 @ framework-9b5d6ec4444c80fa.js:11
aK @ framework-9b5d6ec4444c80fa.js:11
dA @ framework-9b5d6ec4444c80fa.js:11
bR @ framework-9b5d6ec4444c80fa.js:11
bP @ framework-9b5d6ec4444c80fa.js:11
```

### PR DESCRIPTION
**Pull request by TGlide**
## Type of Pull Request

- [X] Bug fix
- [ ] Enhancement

Related Issue #s or links (if any): 
Closes #30 

## Description of Changes
Adds a error handler on URL encode tool:

https://user-images.githubusercontent.com/26071571/194366177-ca86eee7-b147-4908-a1b4-0fe71d608820.mp4

### CODE REVIEW

File: pages/url-encode.tsx [hunk 1]
```diff
@@ -126,16 +131,32 @@ export default function URLEncodeDecode() {
...
             }}
             multiline
           />
           <Box
             display='flex'
+            alignItems='center'
             flexWrap='wrap'
             justifyContent='end'
           >
+            {decodeError && (
```
Comment (dlford) [inline pages/url-encode.tsx:151]: Can we put this on its own below the buttons? Because at 375px width for example, the error message makes the buttons jump around.

**Review by dlford — CHANGES_REQUESTED** [review]
@TGlide great job on this! Just one minor change if you don't mind.

File: pages/url-encode.tsx (hunk 1 above)
Comment (TGlide) [reply pages/url-encode.tsx:151]: Sure thing!

Comment (TGlide) [reply pages/url-encode.tsx]: image

Comment (dlford) [reply pages/url-encode.tsx]: Excellent, thanks!
